version: ~> 1.0
language: node_js
node_js:
  - 14
  - 12
  - 12.0.0
notifications:
  email: false
import:
  - source: travi/.travis-ci:authenticated-semantic-release.yml
after_success: npm run coverage:report
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
