language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev
notifications:
  email: false
install:
  - npm install
  - gem install travis
before_script: 'npm run greenkeeper:update-lockfile'
after_script: 'npm run greenkeeper:upload-lockfile'
env:
  global:
    - FORCE_COLOR=1
    - NPM_CONFIG_COLOR=always
    - GK_LOCK_COMMIT_AMEND=true
