dist: xenial
language: node_js
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+(@(alpha|beta))?)?$/
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release@beta
  on:
    all_branches: true
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
