language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
install:
- npm ci
- gem install travis
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: UlckUS0Sme9M8HhvCG02jx5j8XcA2aQZv6jr2y83g/aJhfQtXRDKjSp8XL94YvUohUg9eOT0dNN1Gs7L+tteXm3uU6pFhcGTKaNNvK6mPhbgSnCH3eWl6u5HPNL2hOVwMytCFX1UIDz9gNcl9nT2D1eHuUR/Z4mbHUYnT5Iqoed3uvvS+NYoDfPNbX3gAWwKPEYJBaPH23tGiNax4LiqkuV7DH0wB9gKdwDV+MrofrsCVvWhdSqu5Qf4rw0FHP33o4cklNs8kxsYl2BsMuDBBjmUzfdx8rOkr8Ot/vfS7LDJ85XJED8aY9jA2uMBE5LpO3SbQy9BSYGOlCwUUEVTxr71hp36k0ucz3m0mgfBAEbXf6r0fvkv0m6XvDhSPG7sJasYyGzwzYd6seMv70o/9OrTpcmG+hlU18JuC9EgyMZU3cj2CnwAAjta4A1tAUs6Y6KkGYgdEX/WwnxqAQRy+1yAgX066FMfcETGH1OQYbzlX+7dBqnd8WkwXnOflEMatOUyiJa4zMQmQFkSogGd6AESxwWVA6ZMU2NmWa8oqWdV1T+rj4IBNjIn7PUv1yckiSkIgUyF1fOZB7MGcBD68d+fOdOTS5SPWCfFKdQMwY/Uv9UWLwXEgpTmU2Zs++771wOvLYC3S82ThOgqoru4CHvLZnMSgE1kp1SMiG+eu7Q=
  - secure: CjVla9jOmPii/7ASQscXf+JLRJKoGCsq+isPac6ZDBl6gtu9ognIhStk8EMz5FM1akqjBE+HgsI/lUXGlNGsVUHtxNSrLot2VGXJDFzwbCHurgVTm7VlnGXS1q52PIgrZ6mDpi6nlIov67Hx7bVj6bfoP3KVnHgiMJJsVAXULPk7ynEv6W7D5d2QrrOzHUoIYWHtUBiJttkAVDBVuB2+KErA4Pn+9x8nY4uH+RcUzdEI8DWi2lpV51NUWHJI/5CotV93Ab/IIm9GLiyp8yruGKNMEAcFx6Q46aYRGKRErYplPBZn1zktT1YZsZdaFHGi12asrPGf10Rqrkm+I+xuzYZf//16eVIiJIADvX3AFJmX1rcH9OlYNUTK8Ruk24oDafjHh4HQWvycYXOsEd9MJFOgJshKtybg4+PuGK+8notIN7zZdSo2fGgJH3JXRZy0EpjoqnYeJ6KhDFUaaPmtBMUHLvD3xg/nGGSjyp4ux9Zm/VvGEsHI/GSclVYfyKwRXjsCR7HeDU9BzdEXUG5K5fFTHcf+MNzn/PC2PMYkGIT5F1gO5E6G1J7IvqHNxoFn7ytgrkqiHrTa9aa8lTTlScHdhcQGA8pZwyVFDIDN5Y82zsvsI6Hh/n5L/Y2uGB7txkIh+aBTVj59gPRp22gqthjVEQQ0Ty+pUhlw7g743Pw=
