name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - run: npm test
      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 18.17.0
          - 20.6.1
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm clean-install
      - run: npm test
  release:
    needs:
      - verify
      - verify-matrix
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}  
      
  # separate job to set as required in branch protection,
  # since the build names above change each time Node versions change
  workflow-result:
    runs-on: ubuntu-latest
    needs:
      - verify
      - verify-matrix
    if: ${{ !cancelled() }}
    steps:
      - name: All matrix versions passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some matrix version failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
