name: Node.js CI
'on':
  push:
    branches:
      - master
      - alpha
      - beta
      - 'renovate/**'
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: 'echo ::set-output name=NVMRC::$(cat .nvmrc)'
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - uses: bahmutov/npm-install@v1
      - run: npm test
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_PUBLISH_TOKEN }}'
      - name: Upload coverage data to Codecov
        run: 'npm run coverage:report'
