name: Release
'on':
  push:
    branches:
      - alpha
  workflow_dispatch: {}
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - name: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
